name: Waka Readme

on:
  schedule:
    # Runs daily at 12:30 AM IST (which is 7 PM UTC)
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to update the README

    steps:
      - name: Update waka-readme-stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}  # Set this in repo secrets
          GH_TOKEN: ${{ secrets.GH_PAT }}                    # Use your Personal Access Token here
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_COMMIT: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
